import { TASK_STATUS, type ITask } from './tasks.types';

export const mockTasks: ITask[] = [
  {
    id: '1',
    project_id: 'p1',
    epic_id: 'e1',
    task_id: 'TM-20',
    title: 'Design initial wireframes for dashboard',
    description: 'Create high fidelity Figma mockups for the project taskboard',
    status: TASK_STATUS.TODO,
    created_at: '2026-08-10T10:00:00Z',
    due_date: '2026-08-20T00:00:00Z',
    epic: { id: 'e1', title: 'User Interface Redesign', epic_id: 'EP-1' },
    created_by: { id: 'u1', name: 'Haidy Hesham', email: 'haidy@example.com', department: 'Engineering' },
    assignee: { id: 'u1', name: 'Haidy Hesham', email: 'haidy@example.com', department: 'Engineering' },
  },
  {
    id: '2',
    project_id: 'p1',
    epic_id: 'e1',
    task_id: 'TM-21',
    title: 'Setup Redux state slice for taskboard',
    description: 'Implement async thunks and reducers for fetching tasks by status',
    status: TASK_STATUS.IN_PROGRESS,
    created_at: '2026-08-11T12:00:00Z',
    due_date: '2026-08-15T00:00:00Z',
    epic: { id: 'e1', title: 'User Interface Redesign', epic_id: 'EP-1' },
    created_by: { id: 'u1', name: 'Haidy Hesham', email: 'haidy@example.com', department: 'Engineering' },
    assignee: { id: 'u2', name: 'Omar Ali', email: 'omar@example.com', department: 'Product' },
  },
  {
    id: '3',
    project_id: 'p1',
    epic_id: 'e2',
    task_id: 'TM-22',
    title: 'Fix responsive layout for mobile navigation',
    description: 'Ensure drawer menu opens smoothly on small screens',
    status: TASK_STATUS.BLOCKED,
    created_at: '2026-08-12T08:30:00Z',
    due_date: '2026-08-14T00:00:00Z',
    epic: { id: 'e2', title: 'Mobile Optimizations', epic_id: 'EP-2' },
    created_by: { id: 'u1', name: 'Haidy Hesham', email: 'haidy@example.com', department: 'Engineering' },
    assignee: { id: 'u1', name: 'Haidy Hesham', email: 'haidy@example.com', department: 'Engineering' },
  },
  {
    id: '4',
    project_id: 'p1',
    epic_id: 'e1',
    task_id: 'TM-23',
    title: 'Unit test authentication flow',
    description: 'Write Jest tests for login and sign-up form validations',
    status: TASK_STATUS.DONE,
    created_at: '2026-08-05T09:00:00Z',
    due_date: '2026-08-10T00:00:00Z',
    epic: { id: 'e1', title: 'User Interface Redesign', epic_id: 'EP-1' },
    created_by: { id: 'u1', name: 'Haidy Hesham', email: 'haidy@example.com', department: 'Engineering' },
    assignee: { id: 'u3', name: 'Sara Ahmed', email: 'sara@example.com', department: 'QA' },
  },
];
